### PR TITLE
Checking in files for stress testing, removed comments in other files

### PR DESCRIPTION
**Pull request by bshresthap**
checking in files for stress testing, removed comments and included .env configurations

### CODE REVIEW

**Comment by bshresthap** [comment]
@danielharmon Can you please review PR https://github.com/sdc-jackson/user-service/pull/5 ? This is related to scripts check in for stress testing and removed comments from some other files. Thank you!

**Comment by bshresthap** [comment]
@danielharmon Can you please review PR https://github.com/sdc-jackson/user-service/pull/5 ? This is related to scripts check in for stress testing and removed comments from some other files. Thank you!

**Review by danielharmon — APPROVED** [review]
Looks good, mostly cleanup

Good idea to have the scripts for artillery

**Comment by bshresthap** [comment]
> Looks good, mostly cleanup
> 
> Good idea to have the scripts for artillery
Thanks Danny. I am using K6.

**Pull request merged**
